services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pgcrypto.sql:/docker-entrypoint-initdb.d/init-pgcrypto.sql

volumes:
  postgres_data: